##################SUPER ADMIN APIS#################
#############GET ACTION LOGS############
GET {{host}}/super-admin/actions
Content-Type: application/json
Authorization: {{superAdminToken}}


#################APPROVE ACTION BY ACTION ID FOR USER###############
PUT {{host}}/super-admin/actions/approve
Content-Type: application/json
Authorization: {{superAdminToken}}

{
  "provider": "user",
  "action_id": 2
}

#################APPROVE ACTION BY ACTION ID FOR TWEET###############
PUT {{host}}/super-admin/actions/approve
Content-Type: application/json
Authorization: {{superAdminToken}}

{
  "provider": "tweet",
  "action_id": 2
}